import { assetUrl } from "../assets/url.js";
const chain = ["medium", "heavy", "kickHeavy", "special1", "special2", "special3", "super"];
export const gorr = {
    id: "gorr",
    name: "GORR",
    title: "O Devorador",
    style: "Grappler brutal — armadura, command grab e dano explosivo",
    color: "#5b2f22",
    accent: "#d46a35",
    portrait: assetUrl("/fighters/gorr.webp"),
    stats: { speed: 205, backSpeed: 145, jump: 650, maxHealth: 1280, defense: 1.28, strength: 1.3, range: 0.86, weight: 1.4, dashSpeed: 500 },
    ratings: { power: 10, speed: 3, defense: 9, range: 2 },
    lore: "Um campeão de fossos que transformou correntes de prisão em armas. Gorr não persegue a vitória: ele a arrasta até si.",
    introLine: "Chegue mais perto. Eu termino rápido.",
    winLine: "Ainda estou com fome.",
    difficulty: 2,
    specials: ["special1", "special2", "special3"],
    super: "super",
    finishes: [
        { id: "finish1", name: "Mesa do Carrasco", command: "66H", description: "Atravessa a guarda e encerra com um impacto brutal." },
        { id: "finish2", name: "Último Banquete", command: "236S", description: "Prende o oponente nas correntes e finaliza a execução." },
    ],
    combos: [
        { id: "g_b1", name: "Quebra-Ossos", level: "basic", sequence: ["light", "medium", "heavy"], description: "Confirma golpes curtos no pesado." },
        { id: "g_b2", name: "Peso Morto", level: "basic", sequence: ["kickLight", "kickHeavy"], description: "Baixo curto seguido do pisão." },
        { id: "g_i1", name: "Sem Escapatória", level: "intermediate", sequence: ["light", "heavy", "special1"], description: "Pesado cancelado na investida blindada." },
        { id: "g_i2", name: "Correntes", level: "intermediate", sequence: ["medium", "special2"], description: "Pressão curta para command grab." },
        { id: "g_a1", name: "Banquete", level: "advanced", sequence: ["light", "medium", "heavy", "special1", "super"], description: "Rota de dano máximo com Super." },
        { id: "g_air", name: "Queda do Devorador", level: "air", sequence: ["aerial", "heavy"], description: "Ataque aéreo para confirmação pesada." },
        { id: "g_c1", name: "Fome Antiga", level: "counter", sequence: ["counter", "special2"], description: "Parry para agarrão de comando." },
    ],
    moves: {
        light: { id: "light", name: "Martelo Curto", type: "normal", button: "light", damage: 60, range: 70, startup: 5, active: 3, recovery: 9, hitStun: 12, blockStun: 7, knockback: 105, priority: 2, meterGain: 8, superGain: 4, cancelInto: chain, height: "mid", hitstop: 4 },
        medium: { id: "medium", name: "Ombro de Ferro", type: "normal", button: "medium", damage: 86, range: 84, startup: 8, active: 4, recovery: 13, hitStun: 15, blockStun: 10, knockback: 155, priority: 3, meterGain: 10, superGain: 5, cancelInto: ["heavy", "kickHeavy", "special1", "special2", "special3", "super"], height: "mid", hitstop: 5 },
        heavy: { id: "heavy", name: "Punho do Abismo", type: "normal", button: "heavy", damage: 138, range: 96, startup: 14, active: 6, recovery: 21, hitStun: 20, blockStun: 13, knockback: 285, priority: 5, meterGain: 13, superGain: 7, cancelInto: ["special1", "special2", "super"], height: "mid", armor: true, hitstop: 9 },
        kickLight: { id: "kickLight", name: "Canela de Ferro", type: "normal", button: "kickLight", damage: 54, range: 68, startup: 6, active: 3, recovery: 11, hitStun: 11, blockStun: 6, knockback: 95, priority: 2, meterGain: 7, superGain: 3, cancelInto: ["medium", "heavy", "special1"], height: "low", hitstop: 3 },
        kickHeavy: { id: "kickHeavy", name: "Pisão do Devorador", type: "normal", button: "kickHeavy", damage: 142, range: 82, startup: 16, active: 6, recovery: 23, hitStun: 22, blockStun: 14, knockback: 330, priority: 5, meterGain: 12, superGain: 6, cancelInto: ["special1", "super"], height: "low", knockdown: true, hitstop: 9 },
        aerial: { id: "aerial", name: "Queda do Colosso", type: "aerial", button: "heavy", damage: 94, range: 88, startup: 8, active: 8, recovery: 10, hitStun: 14, blockStun: 9, knockback: 195, priority: 4, meterGain: 9, superGain: 4, height: "high", airOk: true, hitstop: 5 },
        special1: { id: "special1", name: "Investida Carniceira", type: "special", command: "66H", damage: 175, range: 132, startup: 12, active: 8, recovery: 20, hitStun: 18, blockStun: 11, knockback: 360, priority: 6, meterGain: 5, superGain: 10, cost: 30, cancelInto: ["super"], height: "mid", advance: 470, armor: true, hitstop: 7 },
        special2: { id: "special2", name: "Abraço da Cova", type: "special", command: "236T", damage: 205, range: 58, startup: 7, active: 3, recovery: 28, hitStun: 0, blockStun: 0, knockback: 420, priority: 9, meterGain: 5, superGain: 11, cost: 35, height: "mid", grab: true, commandGrab: true, knockdown: true, hitstop: 10 },
        special3: { id: "special3", name: "Tremor de Correntes", type: "special", command: "22S", damage: 118, range: 350, startup: 18, active: 5, recovery: 26, hitStun: 16, blockStun: 10, knockback: 240, priority: 4, meterGain: 4, superGain: 9, cost: 35, height: "low", projectile: "wave", knockdown: true, hitstop: 6 },
        super: { id: "super", name: "Banquete Final", type: "super", command: "236236H", damage: 385, range: 92, startup: 9, active: 18, recovery: 32, hitStun: 34, blockStun: 15, knockback: 520, priority: 10, meterGain: 0, superGain: 0, superCost: 100, cost: 0, height: "mid", hits: 6, invuln: 8, grab: true, commandGrab: true, knockdown: true, hitstop: 13, advance: 100 },
        throw: { id: "throw", name: "Arremesso de Corrente", type: "throw", button: "throw", damage: 165, range: 55, startup: 5, active: 3, recovery: 24, hitStun: 0, blockStun: 0, knockback: 390, priority: 9, meterGain: 10, superGain: 8, grab: true, knockdown: true, height: "mid", hitstop: 8 },
        counter: { id: "counter", name: "Casca de Ferro", type: "counter", command: "22L", damage: 105, range: 75, startup: 4, active: 10, recovery: 22, hitStun: 19, blockStun: 0, knockback: 220, priority: 7, meterGain: 12, superGain: 8, invuln: 10, armor: true, height: "mid", hitstop: 7 },
        taunt: { id: "taunt", name: "Ainda com Fome", type: "taunt", button: "taunt", damage: 0, range: 0, startup: 4, active: 1, recovery: 42, hitStun: 0, blockStun: 0, knockback: 0, priority: 0, meterGain: 20, superGain: 12, height: "mid" },
    },
};
